// frontend-react/src/components/molecules/AudioPlayer.tsx
import React, { useRef, useState, useEffect } from 'react'

interface AudioPlayerProps {
  audio?: string
}

const AudioPlayer: React.FC<AudioPlayerProps> = ({ audio }) => {
  const audioRef = useRef<HTMLAudioElement>(null)
  const [progress, setProgress] = useState(0)

  const playAudio = () => {
    audioRef.current?.play().catch((err) => {
      console.error('Error playing audio:', err)
    })
  }

  useEffect(() => {
    const audioEl = audioRef.current
    if (!audioEl) return

    const updateProgress = () => {
      if (!audioEl.duration) return
      setProgress((audioEl.currentTime / audioEl.duration) * 100)
    }

    const resetProgress = () => setProgress(0)

    audioEl.addEventListener('timeupdate', updateProgress)
    audioEl.addEventListener('ended', resetProgress)

    return () => {
      audioEl.pause()
      audioEl.removeEventListener('timeupdate', updateProgress)
      audioEl.removeEventListener('ended', resetProgress)
    }
  }, [audio])

  return (
    <div className="flex items-center mt-4 gap-2">
      <button
        className="text-2xl"
        onClick={playAudio}
        aria-label="Play audio"
        type="button"
      >
        ▶
      </button>
      <div
        className="w-full h-2 bg-gray-300 rounded"
        role="progressbar"
        aria-valuenow={progress}
        aria-valuemin={0}
        aria-valuemax={100}
      >
        <div
          className="h-2 bg-blue-400 rounded"
          style={{ width: `${progress}%` }}
        ></div>
      </div>
      <audio ref={audioRef} src={audio} preload="auto" />
    </div>
  )
}

export default AudioPlayer

// frontend-vue/src/components/molecules/AudioPlayer.vue
<template>
  <div class="flex items-center mt-4 gap-2">
    <button class="text-2xl" @click="playAudio">&#9654;</button>
    <div class="w-full h-2 bg-gray-300 rounded">
      <div class="h-2 bg-blue-400 rounded" :style="{ width: progress + '%' }"></div>
    </div>
    <audio ref="audioPlayer" :src="audio" @timeupdate="updateProgress" @ended="onEnded"></audio>
  </div>
</template>
<script setup lang="ts">
import { ref } from 'vue'

defineProps<{ audio?: string }>()

const audioPlayer = ref<HTMLAudioElement | null>(null)
const progress = ref(0)

const playAudio = () => {
  if (audioPlayer.value) {
    audioPlayer.value.play().catch((err: any) => {
      console.error('Erro ao tentar tocar áudio:', err)
    })
  }
}

const updateProgress = () => {
  const audio = audioPlayer.value
  if (!audio) return

  progress.value = (audio.currentTime / audio.duration) * 100
}

const onEnded = () => {
  progress.value = 0
}
</script>
