// frontend-react/src/components/molecules/UserThumbnail.tsx
import React from 'react'

interface UserThumbnailProps {
  name: string
}

function formatUserName(name: string) {
  if (!name) return
  const parts = name.trim().split(' ')
  if (parts.length === 0) return ''
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase()
  return (parts[0][0] + parts[1][0]).toUpperCase()
}

const UserThumbnail: React.FC<UserThumbnailProps> = ({ name }) => {
  return (
    <div className="flex items-center justify-center w-12 h-12 bg-blue-300 rounded-full">
      <span className="font-semibold text-slate-800">{formatUserName(name)}</span>
    </div>
  )
}

export default UserThumbnail

// frontend-vue/src/components/molecules/UserThumbnail.vue
<template>
  <div class="flex items-center justify-center size-12 bg-blue-300 rounded-full">
    <span class="font-semibold text-slate-800">{{ formatUserName(name) }}</span>
  </div>
</template>
<script setup lang="ts">
import { formatUserName } from '@/misc/format'
defineProps<{ name: string }>()
</script>
